version: '3.1'

services:
  db:
    container_name: sse_basic_db
    image: postgres
    environment:
      POSTGRES_DB: sse_basic
      POSTGRES_USER: sse
      POSTGRES_PASSWORD: sse
    ports:
      - '55432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    container_name: sse_basic_app
    build: .
    command: pnpm start:dev
    ports:
      - '53000:3000'
    volumes:
      - .:/app
    depends_on:
      - db

volumes:
  db-data:
